---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: create-env
  labels:
    app: bookinfo
spec:
  params:
    - name: eventtype
  check:
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "test $(params.eventtype) = opened"]
---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: delete-env
  labels:
    app: bookinfo
spec:
  params:
    - name: eventtype
  check:
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "test $(params.eventtype) = closed "]
    