---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: generic-pipeline
  labels:
    app: bookinfo
spec:
  params:
    - name: pathToDockerFile
      default: 'Dockerfile'
      type: string
      description: Path to the dockerfile to build
    - name: pathToContext
      default: '.'
      type: string
      description: Path to the build context
    - name: serviceName
      description: Name of project being built
  resources:
    - name: source-repo
      type: git
    - name: service-image
      type: image
  tasks:
  - name: build-service
    taskRef: 
      name: build-docker-image-from-git-source
    params:
      - name: pathToDockerFile
        value: "$(params.pathToDockerFile)"
      - name: pathToContext
        value: "$(params.pathToContext)"
    resources:
      inputs: 
        - name: source-repo
          resource: source-repo
      outputs:
        - name: builtImage
          resource: service-image
  - name: notify-build-success
    taskRef:
      name: notify-slack
    params:
      - name: message
        value: $(params.serviceName) built
    runAfter: 
      - build-service
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-pipeline
  labels:
    app: bookinfo
spec:
  params:
    - name: eventtype
    - name: branch
    - name: pusher
    - name: latestcommit
  resources:
    - name: source
      type: git
    - name: image
      type: image
  tasks:
  - name: spawn-service-builds
    taskRef: 
      name: spawn-service-builds
    params:
      - name: branch-ref
        value: $(params.branch)
    resources:
      inputs: 
        - name: source
          resource: source
        - name: image
          resource: image
  - name: notify-build-invoked
    taskRef:
      name: notify-slack
    params:
      - name: message
        value: "$(params.pusher) triggered a build on $(params.branch) with a $(params.eventtype). Commit: $(params.latestcommit)"
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pr-pipeline
  labels:
    app: bookinfo
spec:
  params:
    - name: eventtype
    - name: pr-number
    - name: giturl
    - name: pathToManifests
    - name: branch
  tasks:
  - name: create-environment
    taskRef:
      name: create-environment
    params:
      - name: namespace
        value: pr-$(params.pr-number)
      - name: giturl
        value: $(params.giturl)
      - name: pathToManifests
        value: $(params.pathToManifests)
      - name: branch
        value: $(params.branch)
    conditions:
      - conditionRef: create-env
        params:
          - name: eventtype
            value: $(params.eventtype)
  - name: delete-environment
    taskRef:
      name: delete-namespace
    conditions:
      - conditionRef: delete-env
        params:
          - name: eventtype
            value: $(params.eventtype)
    params:
      - name: namespace
        value: pr-$(params.pr-number)
  - name: notify-build-invoked
    taskRef:
      name: notify-slack
    params:
      - name: message
        value: "$(params.eventtype) the environment for PR-$(params.pr-number)"
