---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trigger-service-acct
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-service-acct
secrets:
  - name: containerregcred
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-create-resources
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "eventlisteners", "triggerbindings", "triggertemplates", "tasks", "taskruns"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-triggers
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: trigger-service-acct # Name is case sensitive
  namespace: tekton-pipelines
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: tekton-create-resources # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io