---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: details-pipeline-run
spec:
  serviceAccountName: ecr-service-acct
  pipelineRef:
    name: generic-pipeline
  params:
    - name: "pathToDockerFile"
      value: "/workspace/docker-source/src/details/Dockerfile"
    - name: "pathToContext"
      value: "/workspace/docker-source/src/details/"
    - name: "deploymentYamlPath"
      value: "/workspace/source/platform/kube/bookinfo-details.yaml"
  resources:
    - name: source-repo
      resourceRef:
        name: bookinfo-git
    - name: service-image
      resourceSpec:
        type: image
        params:
        - name: url
          value: <IMAGE-TAG>