---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: ratings-pipeline-run
spec:
  serviceAccountName: ecr-service-acct
  pipelineRef:
    name: generic-pipeline
  params:
    - name: serviceName
      value: Ratings
    - name: "pathToDockerFile"
      value: "/workspace/source-repo/src/ratings/Dockerfile"
    - name: "pathToContext"
      value: "/workspace/source-repo/src/ratings/"
  resources:
    - name: source-repo
      resourceSpec:
        type: git
        params:
        - name: revision
          value: <branch>
        - name: url
          value: https://github.com/CSTDev/bookinfo
    - name: service-image
      resourceSpec:
        type: image
        params:
        - name: url
          value: <IMAGE-TAG>
                    